#ifndef _MULTIBOOT2_H_
#define _MULTIBOOT2_H_

#define MULTIBOOT2_HEADER_MAGIC              0xE85250D6
#define MULTIBOOT2_ARCHITECTURE_I386         0
#define MULTIBOOT2_HEADER_TAG_END            0
#define MULTIBOOT2_HEADER_TAG_INFO_REQUEST   1
#define MULTIBOOT2_HEADER_TAG_FRAMEBUFFER    5
#define MULTIBOOT2_HEADER_TAG_MODULE_ALIGN   6
#define MULTIBOOT2_HEADER_TAG_FLAG_REQUIRED  0
#define MULTIBOOT2_HEADER_TAG_FLAG_OPTIONAL  1
#define MULTIBOOT2_TAG_TYPE_FRAMEBUFFER      8
#define MULTIBOOT2_TAG_TYPE_ACPI_NEW         15
#define MULTIBOOT2_TAG_TYPE_EFI_MMAP         17

#endif // MULTIBOOT2_H_